#
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
#
variables:
    - group: Credentials
    
trigger:
- master
- azure-pipeline

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node'

- bash: |
    set -ex
    curl -sL https://firebase.tools | bash
    npm install
  displayName: 'Install'

- bash: |
    set -ex
    npm run build
  displayName: 'Build'

- bash: |
    set -ex
    firebase deploy
  displayName: 'Deploy to Staging'
  env:
    FIREBASE_TOKEN: $(FIREBASE_TOKEN)
